name: Container Outbound Call

on:
  workflow_dispatch:
    
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: block
          allowed-endpoints: 
            github.com:443
      - uses: actions/checkout@v2.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: sudo iptables -L -v -n 