name: Super Linter

on:
  workflow_dispatch:
    
permissions: read-all

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      statuses: write # for github/super-linter to mark status of each linter run
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          allowed-endpoints: 
            github.com:443
            bogus.domain.stepsecurity.io:443 # cause and test revert behaviour
      - uses: actions/checkout@v2.4.0
      - uses: github/super-linter@v4.8.5
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_BASH: true
          # VALIDATE_BASH_EXEC: true
          # VALIDATE_EDITORCONFIG: true
          # VALIDATE_SHELL_SHFMT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
